# Generated by Django 5.2.1 on 2025-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Full description of the event.')),
                ('date_time', models.DateTimeField(help_text='The start date and time of the event.')),
                ('location', models.CharField(help_text='Physical address or online meeting link.', max_length=150)),
                ('banner_url', models.URLField(blank=True, help_text='Link to a placeholder image or event banner.', null=True)),
                ('is_upcoming', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
