# Generated by Django 5.2.1 on 2025-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='A short, catchy summary of the project.', max_length=250)),
                ('description', models.TextField()),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('FULLSTACK', 'Full Stack'), ('DESIGN', 'Design')], default='FULLSTACK', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contributors', models.ManyToManyField(blank=True, related_name='contributed_projects', to='members.contributor')),
            ],
        ),
    ]
