# Generated by Django 5.2.8 on 2025-11-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Short bio or description of their role/skills.')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='contributor_photos/')),
            ],
        ),
    ]
